language: elixir
cache:
  directories:
    - _build
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - MAIN_BRANCHES="master" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    - secure: "cm8F6poDy8DYOHjUDdJ4lqeFN9jAjwCeQlyvrM6mgPjthGEdjzUp7+4YkBPDrDkyj6KkBXyFIAizmp/YKWifQBs0C4J6wfXXdB5c1z39K4DY9omdzZ+r4o2EsmUBG2qHPhUhq9mT+BHGA+GmgzaaZzVzTLvo1XnF0voP+dAmkAcujhIQW7pa8Hi80EOHuHRpKRZ1Yo5VnmdktZU+AHSR5de8QP71nfmXTOaXWVM/I1OoyIaP/9X9vl5qsy0VdAWwI4+5mUzVgXcggYIBBbtNvwJ+CSZdOl5NzRu8mxcHu4YFNRejRf9rENlF4QmdmVfTvIiOGnyVjZudRsP6CahjEpXxICRub+PanXGjwOIzwsswnXZmyYI/ZZdViXRJ25nBAe2u8H+67v7PA9jdlKy4X4O7kCENSPaxFuTD7cRxgfDLxOfr+tlvagFPaXSPQ7ZZYxMY0xVKpsl4Ng1gFVywSeigTgTwTZDf4494nW0Kwg78rnnDVUdWNS4k4WT933GmSxl3EwootuvWbLPMAqJX/uPIj7LQ2iD2jXrZn2s3a3eXNh9PWmsxzurSSpr2CXbkmOOoqeOgCXafP/98X/kswBojaHh3wZj+3+D7dWr95fYluz2o7tISpOCSKxO9LhRE5JxSI6CfH5ddCJn1Eyf1MDcPRguCTOCZF1ttreVWVj8="
    - secure: "TdmFaQMePgUPDrvzhQzUW2YKL3sQdI0W8Nf2ToF6j9/ev5JIjUhC5PJzLVMBw+MQBEnRmsP/Xma1Ui7xa0iC48PR5+F8Q/uHnBlRpF+YsLSnRvc06UUqeC2mQQeCBy0DoL2OHrkgPrNmPDtXMowfY/miXjkwsxx/uRJsUO+d0uArx38bT6iSJKjeMhiZd+IjwgMlfpzB6eyixYss0koqKQgn7XINtXynfwpWeZldLAOXVL9oHPOJhGc4g/fST/BASQlO23wpnL0poTxRpFrfU6Xj0gK6++eQJ+pDBAwq8KCpQpZ83D7lmZPDw1seyhVJ7HJ3ncPMKhyENnGot6bE8oQrs1G5eyuVbK8WK8ByRT1PPxM0K6kZMEzXln2LiuYeVpGUI/bo2rJ75V4yOzb6jqdNdL2wmCp//jy9OzU7Kj4HQlaLd6wgr0snehjX3iCsqh5HhaIwqZnGGdS/JdZI8+qVmNRsjp5EedttKD5CqLhMnVt8oD8GjJB8gpwTB4cdWatO9TBGzImSbqInjvwk48LLNSFPFjokF9gFd9aQ+1ikc2QWa1bOyaXO7YpUmb5h1w0IprrfK9exVkEOaIHh3ovQXo4yNOwIAf0aI7amVdD6zFYIDZtdRJKfH4IN3HfeboN52D+++if6TzfPqguue7lg+0+Obm1HJupNzruOELk="
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose DB to Docker container
  - sudo ./bin/ci/init-db.sh
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
  - if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then echo "[E] Container is not started\!"; docker logs ehealth --details --since 5h; exit 1; fi;
after_failure:
  - docker logs ehealth --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh
