language: elixir
cache:
  directories:
    - _build
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    - secure: d8qOWmXymyCFiSi+h2IgGCr+v87QAhMnEFoq/ATV6zO7tURZSjG0cjFh8yJnCBJC4nDq+avKQZ8NVm7g2LSKTyBu13FWw9lm7eRc+HBg/tI8T4ngIS+pMdhcFlr2ZxZVEB6R2Ob32JWxdoC5JKuBHWgTzD28WBxGqCId0fxdve0Kdb1qcqXN44eiR31gyZgwc1Q8F4pn61d4lvH4efL8BtlJlewYgRS66zNE02+QPtHRW6Kv3ghQ0nDfiJl1acU8kvg3NflcAmQeUj0hOWqtEYhEzCQn8hWYcFyv7hHYIpOikeC2omg+ZenU8CGKNRzseHxer/AmILrBPRGCYADxn4MYmOw5Z+KYWWDCyo6QkVPxFcaaxLtaZKwtWCh6AGDDScYsHgKA7Yfx+GssGHo3C74FM6oBPoAirhn2tUDeK/JoNzC7a15Ma4iVUyvF+xytK6G5blp2z0m8wLxKwybIaGLu64kSDQtaM5oBg6WdJJyckuc07/yIhMle88498fzVbMiFyIZ8m4gY62E9/1Ic5m+KYT68/4q5OQ2lVEuTlkVFM3GgXi2y/C7UUW9Efdbm08R28I6C7QAn3COyZBIz+zFxUVY3xwmPCalHAGa0I/JNHv+fCVd9xxBw5sexAMUaWXiDO8Mg9v83mkxcKXhirGoT5lAMrRSWdwR/vUUJ8NU=
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Run Docker container
  - ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
  - if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then echo "[E] Container is not started\!"; docker logs ehealth --details --since 5h; exit 1; fi;
after_failure:
  - docker logs ehealth --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh