language: elixir
cache:
  directories:
    - _build
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    - secure: "ayklvzkuBh9pv9GvSFYp306oRWp/V+9f2LNGYSweLkRWdc0MxXDPIrV+zZLDKI/Yi4zHJl94eafGuGDz2xnk4rQGcEREcW4tmBAmXvsNCcnT9/z6oAfRifkda4ZFB4IZ9Azq5oAhJ9s/3ZJc9eFUYoy+fWbZerJcoiO9r75MnklRAUxPE0vJyplUU2Sza01N77QKiySA7MB2MbIKQbSZ3otqGjEtREkMJjZmGgMboS9cBlakoUZ2jv2beSFOEyEDLhwlJs/DgarUKajkeEVXQ72WnOXbsUeFFHeScn1imEsdLX2cRbNZk14KoAQx7TiZdsyrCtm3HDECBrN8vD8Wje/QfNPmsd5XjIV89SnGY3EdPAaVa0lK0Xb5oTbA9f0SaxaPBbQJDanc9g7DFTg42jCDnlzzWsVByVE7qkkTCkS6JEX1L8Dd+84fsqWWt3owM9BU8+7aAfgPf/XrCqkXq146JJ0D7yyFfJiy1B1vafjunQAk1p65Hy+3qmcCOuUnCPX5qVBP6xiJkrkMuaKKbsrwrd0nTMuuTyyGAJciGwM1x9VgyQA47UYbmAYqPRom90T2YTNMYYUbmSzWYZBfpgxhOR7cF4zukrVGXHTbsffAvCY7GPPoBVNbZbKem8yUXo1hNIw2S2rnJ37b3fq1SVPqXkoRklQ0UyuIlaI65Kc="
    - secure: "XPS2eTLhy5jGKGhTTtD4aqjZybX7lDzkJkLT5BymtqwSAJ6OK3BoPi+v8Qh5yyhEr77MvfM+mJpnYjZ2r9XdQ+NyGOlyijZt79EsRjYj/oKLz5BXqvOzLPr4hmQney9k0fwE5+5rQygHeRhQ6poYiVrXSmyMLR4POX3XO5SAKvuOCUrjzlFHlxYgCxWe6XH8ZsP1n6IhbE58kI23X9z3eawPrlY3YZO6HDaVCEuY1Urs2lHzn0t6lbGWQWYD3iNn4fUAO2EJNqUZTC+VMU+zUgaJLLgV1yuqzAuMu1vwDUV1csTzKJrVlSc2okzSCBgksEWHiD8dj1hCaiy1vEXMn+zFB33CDtIxptFJGxMidXNUc9fc1GFG7K6VDbLtLiCa8hb2xaSc7aPiDG9hM8QwHPR1Ca/wEmhb0j96NahD82d6euSOk9jvxrWhqcFqnyegWiV4xct0cK/2pYbI/xcWt1LJqc8NUn9ilS2a+gKEzYbJavmCIvuFSBKbwjPD4B0T1xk7pYyk2ANS67n2gpcxkXsF77Q5rSplycInMgpB1z+C1BuKuVNrTKIxCzQacfJk5rez3NbTBimapjaDoTnk6KJNhFZhoyF6fL/ed39vOMbVJj5m7OeetDqUDf+X3EeWdN6BIzJj+LXTbTQVe+Yn033PiVlQ9Aq7J8rd6MHxFSQ="
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose DB to Docker container
  - sudo ./bin/ci/init-db.sh
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
  - if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then echo "[E] Container is not started\!"; docker logs ehealth --details --since 5h; exit 1; fi;
after_failure:
  - docker logs ehealth --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh
